### ISSUE TITLE
The danger of the retain cycle in Binding

### ISSUE THREAD

**Issue by K-Be** [jeremytregunna/Binding#2]
Binding contains strong reference to it's target object. it is very danger.
In example at https://github.com/jeremytregunna/Binding#boilerplate-removal, Cell contains strong reference to nameBinding variable. And nameBinding is created with target the self (the self is instance of Cell):

``` objc
self.nameBinding = [Bind(self, name) relate:Bind(self.nameLabel, text)];
```

It creates retain cycle for Cell and Binding instance.

I think, what the target in Bind should be weak reference.

**Comment by jeremytregunna** [comment]
Thanks for the catch.

**Comment by K-Be** [comment]
In example 

```
self.resultsBinding = [Bind(self.dataStore, results) next:^(NSArray* results) {
self.title = [NSString stringWithFormat:@"Comments (%tu)", [results count]];

[self.tableView reloadData];
 }];
```

also exist the retain cycle for cell, because the block create strong reference to self, the bind copy the block and self create strong reference to the bind.
